### ISSUE TITLE
Can we get the background to all source code to work?

### ISSUE THREAD

**Issue by David-Else** [davidgranstrom/nvim-markdown-preview#2]
Hi, amazing plugin, my brain is blown it has one star only?! All the others are pure bloat.

If my markdown has:
```
```shell
example
```

Then the rendered result in the browser has a background `background-color: #f6f8fa;`, but if it were:
```
```rust
```

Then I get the full-colour syntax (great!), but the background is gone.

I am using:
```
let g:markdown_fenced_languages = ['bash=sh', 'javascript', 'js=javascript', 'json=javascript', 'typescript', 'ts=typescript', 'php', 'html', 'css', 'rust']
```
Somehow your clever plugin is injecting the colors? I don't know what it does, but it would be great to get the background back so it looks the same as GitHub.

![Screenshot from 2021-02-25 15-21-07](https://user-images.githubusercontent.com/12832280/109175134-65f36780-777d-11eb-9ae5-dc662043cb97.png)

**Comment by davidgranstrom** [comment]
@David-Else Thanks!

I had to look into this myself since it was some time ago I wrote this code. It seems that the syntax highlighting is something we get "for free" by generating the html via `pandoc`. 

You can check the supported languages (for highlighting) with this command `pandoc --list-highlight-styles`. 

I had "rust" in that list, and for me the rendered markdown looks like this: 
![Screenshot 2021-02-25 at 17 30 30](https://user-images.githubusercontent.com/672917/109184766-98a65b80-778f-11eb-969e-0b6ccbd2547c.png)
 
So it might just be difference in pandoc versions maybe if you can't see the background?
```
❯ pandoc --version
pandoc 2.7.3
```

You can read about more advanced options here: https://pandoc.org/MANUAL.html#syntax-highlighting

**Comment by David-Else** [comment]
I get:
```
pandoc --version
pandoc 2.11.2

pandoc --list-highlight-styles
pygments
tango
espresso
zenburn
kate
monochrome
breezedark
haddock
```
Your pandoc version is from Jun 2019... the latest is pandoc 2.11.4 (2021-01-22).

I think they have changed things somehow, there is no mention of languages only the color schemes (`pygments` is the default).

If you felt like updating to use the new version and fiddling around with it great, but I understand if you want to leave it alone as you did this a long time ago and probably have better things to do with your time. The extension is pretty much perfect anyway.

**Comment by David-Else** [comment]
I added this plugin to the awesome Neovim collection, if you don't want it there please say so in this pull request before it is approved. Cheers!

https://github.com/rockerBOO/awesome-neovim/pull/42
